POST http://localhost:8080/events/6/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QwQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM5MTcxNjc2LCJ1c2VySWQiOjZ9.piUDVZYfXgJhjjJAny5qVBe2d6KpT6JnDwnawCVG5T4